### PR TITLE
jwt:  token detection from input

### LINKED ISSUE #32: Automatic detection of JWT token within input
As a user, I want the system to automatically detect the JWT token within the provided input, even if it includes prefixes or postfixes like "Bearer ". This improvement will enhance the user experience by eliminating the need to manually extract the token from the input. The improvement will gain advantage over jwt.io.

### PR DESCRIPTION
**Pull request by TheBestTvarynka**
closes #32

### CODE REVIEW

**Comment by TheBestTvarynka** [comment]
@MetaMmodern this is how it works now:

1. It removes the "Authorization" and "Berier" words.
2. Then removed all non-base64 chars.
3. And only then tried to parse it.
4. If your JWT has more than 3 parts (for example, you've pasted JWE), then all other parts after the signature will be rendered but in red

Example:

image

**Comment by MetaMmodern** [comment]
@TheBestTvarynka 

1. Not good yiu hardcoded values. In TG we discussed that token can have different prefixes/suffixes, so it would be better to make it more abstract. If jwt has format like {value}.{value}.{value} then you can just use a regex to parse it out and cut out anything else afterwards(applying that strikethrough).
Moreover, I'd say later you can improve this solution by having iterative check. For instance, if you have something like {nonsense}.{value}.{value}.{value} your regex will parse nonsense.value.value and will show that token is invalid. At this point you can capture all groups of {}.{}.{} And check every one of it. The first one to have parsable json in it will indicate a jwt token start.
2. Okay.

4. nice addition, but it wasn't a requirement.

**Comment by TheBestTvarynka** [comment]
@MetaMmodern check it now

here are a few new examples:

image


image


image

**Comment by MetaMmodern** [comment]
@TheBestTvarynka that's 🔥 ! :shipit:

**Comment by TheBestTvarynka** [comment]
thank you for your feedback :tulip:

**Pull request merged**
